version: '3'
services:
  web:
    build:
      context: .
      args:
        jar: 'build/libs/ons-fwmt-cache-1.0.0-SNAPSHOT.jar'
    depends_on:
      - postgres
      - rabbitRM
      - rabbitGW
    ports:
      - '8026:8026'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres/postgres?currentSchema=fwmtg'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SPRING_LIQUIBASE_URL: 'jdbc:postgresql://postgres/postgres?currentSchema=fwmtg'
      SPRING_LIQUIBASE_PASSWORD: 'password'
      RABBITMQ_HOSTNAME: 'rabbitmq'
  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
  rabbitRM:
    image: rabbitmq:3-management-alpine
    container_name: rabbitRM
    ports:
      - 5672:5672
      - 15672:15672
  rabbitGW:
    image: rabbitmq:3-management-alpine
    container_name: rabbitGW
    ports:
      - 5673:5672
      - 15673:15672
