REVOKE ALL ON ALL TABLES IN SCHEMA fwmtg FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA fwmtg FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE postgres FROM fwmtgsvc;
DROP SCHEMA IF EXISTS fwmtg CASCADE;
DROP ROLE IF EXISTS fwmtgsvc;

CREATE ROLE fwmtgsvc PASSWORD 'fwmtgsvc' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION INHERIT LOGIN;

CREATE SCHEMA fwmtg AUTHORIZATION fwmtgsvc;

GRANT CONNECT ON DATABASE postgres TO fwmtgsvc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fwmtg TO fwmtgsvc;
GRANT ALL ON ALL SEQUENCES IN SCHEMA fwmtg TO fwmtgsvc;
